# Generated by Django 2.2.12 on 2020-04-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('provinceId', models.IntegerField()),
                ('cityName', models.CharField(max_length=200)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='ForeignCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locationId', models.IntegerField()),
                ('continents', models.CharField(max_length=200)),
                ('countryShortCode', models.CharField(max_length=200)),
                ('countryType', models.CharField(max_length=200)),
                ('countryFullName', models.CharField(max_length=200)),
                ('provinceId', models.IntegerField()),
                ('provinceName', models.CharField(max_length=200)),
                ('provinceShortName', models.CharField(max_length=200)),
                ('cityName', models.CharField(max_length=200)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('showRank', models.BooleanField()),
                ('deadRateRank', models.IntegerField(null=True)),
                ('deadCountRank', models.IntegerField(null=True)),
                ('confirmedCountRank', models.FloatField(null=True)),
                ('deadRate', models.FloatField()),
                ('tags', models.CharField(max_length=200)),
                ('statisticsData', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('incrVo', models.CharField(max_length=200)),
                ('sort', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('modifyTime', models.CharField(max_length=200)),
                ('createTime', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '国外',
                'verbose_name_plural': '国外',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('locationId', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceName', models.CharField(max_length=200)),
                ('provinceShortName', models.CharField(max_length=200)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('statisticsData', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
    ]
