# Generated by Django 2.2.12 on 2020-04-15 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '抓取版本',
                'verbose_name_plural': '抓取版本',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('provinceName', models.CharField(max_length=50)),
                ('provinceShortName', models.CharField(max_length=20)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('statisticsData', models.CharField(max_length=500)),
                ('crawler', models.ForeignKey(db_column='crawlerId', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='ncovapi.Crawler')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('continents', models.CharField(max_length=50)),
                ('countryShortCode', models.CharField(max_length=20)),
                ('countryType', models.CharField(max_length=20)),
                ('countryName', models.CharField(max_length=50)),
                ('countryFullName', models.CharField(max_length=50)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('showRank', models.BooleanField(null=True)),
                ('deadRateRank', models.IntegerField(null=True)),
                ('deadCountRank', models.IntegerField(null=True)),
                ('confirmedCountRank', models.FloatField(null=True)),
                ('deadRate', models.FloatField(null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('statisticsData', models.CharField(max_length=500, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('incrVo', models.TextField(null=True)),
                ('sort', models.IntegerField(null=True)),
                ('operator', models.CharField(max_length=50, null=True)),
                ('modifyTime', models.IntegerField(null=True)),
                ('createTime', models.IntegerField(null=True)),
                ('crawler', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='ncovapi.Crawler')),
            ],
            options={
                'verbose_name': '国家或地区',
                'verbose_name_plural': '国家或地区',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('cityName', models.CharField(max_length=50)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('crawler', models.ForeignKey(db_column='crawlerId', on_delete=django.db.models.deletion.CASCADE, to='ncovapi.Crawler')),
                ('province', models.ForeignKey(db_column='provinceId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='ncovapi.Province')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
    ]
