# Generated by Django 2.2.12 on 2020-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForeignCountry',
        ),
        migrations.AddField(
            model_name='city',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='confirmedCountRank',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='continents',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='countryFullName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='countryShortCode',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='countryType',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='createTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='deadCountRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='deadRate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='deadRateRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='incrVo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='modifyTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='operator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='provinceName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='provinceShortName',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='showRank',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='sort',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='statisticsData',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='provinceName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='province',
            name='provinceShortName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='province',
            name='statisticsData',
            field=models.CharField(max_length=500),
        ),
    ]
