# Generated by Django 2.2.12 on 2020-04-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0002_auto_20200410_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='countryName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
