# Generated by Django 2.2.12 on 2020-04-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0003_auto_20200410_0842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('continents', 'countryFullName', 'provinceName', 'cityName')},
        ),
    ]
