# Generated by Django 2.2.12 on 2020-04-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0004_auto_20200410_0853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
