# Generated by Django 2.2.12 on 2020-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0005_auto_20200410_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Country',
        ),
    ]
