# Generated by Django 2.2.12 on 2020-04-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0006_auto_20200410_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家或地区', 'verbose_name_plural': '国家或地区'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='cityName',
        ),
        migrations.RemoveField(
            model_name='country',
            name='provinceId',
        ),
        migrations.RemoveField(
            model_name='country',
            name='provinceName',
        ),
        migrations.RemoveField(
            model_name='country',
            name='provinceShortName',
        ),
    ]
