# Generated by Django 2.2.12 on 2020-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0007_auto_20200410_0923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('continents', 'countryShortCode')},
        ),
    ]
