# Generated by Django 2.2.12 on 2020-04-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0008_auto_20200410_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('locationId', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=50)),
                ('currentConfirmedCount', models.IntegerField()),
                ('confirmedCount', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='ncovapi.Province')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
    ]
