# Generated by Django 2.2.12 on 2020-04-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0009_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'locationId')},
        ),
    ]
