# Generated by Django 2.2.12 on 2020-04-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0011_auto_20200410_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(db_column='provinceId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='ncovapi.Province'),
        ),
    ]
