# Generated by Django 2.2.12 on 2020-04-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0012_auto_20200410_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='province',
            new_name='provinceId',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('provinceId', 'cityName')},
        ),
    ]
