# Generated by Django 2.2.12 on 2020-04-11 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ncovapi', '0014_auto_20200410_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='crawl_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='抓取时间'),
        ),
        migrations.AddField(
            model_name='country',
            name='crawl_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='抓取时间'),
        ),
        migrations.AddField(
            model_name='province',
            name='crawl_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='抓取时间'),
        ),
    ]
